config/routes.rb
Rails.application.routes.draw do
  root "characters#index"
  resources :characters, only: [:new, :create, :destroy]
  get "/characters/search" => "characters#search", as: :search_character
end

app/models/character.rb
class Character < ActiveRecord::Base
  validates :name, presence: true
  validates :character_class, presence: true
  validates :physical, presence: true
  validates :social_skills, presence: true
  validates :magical_abilities, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def index
    @characters = Character.order(:name)
  end

  def new
    @character = Character.new
  end

  def search
    @search_term = params[:term]
    @search_result = Character.where "name like ? or character_class like ? or description like ?", "%#{@search_term}%", "%#{@search_term}%", "%#{@search_term}%"
  end

  def create
    values = params.require(:character).permit :name, :character_class, :description, :physical, :social_skills, :magical_abilities
    @character = Character.new values
    if @character.save
      flash[:notice] = "Character saved successfully"
      redirect_to root_url
    else
      render :new
    end
  end

  def destroy
    id = params[:id]
    Character.destroy id
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Class</th>
      <th>Description</th>
      <th>Physical</th>
      <th>Social skills</th>
      <th>Magical abilities</th>
    </tr>
  </thead>
  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.character_class %></td>
        <td><%= character.description %></td>
        <td><%= character.physical %></td>
        <td><%= character.social_skills %></td>
        <td><%= character.magical_abilities %></td>
        <td><%= button_to "Remove", character, method: :delete, data: { confirm: "Remove #{character.name}?" }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Criate new character", new_character_path %>

app/views/characters/new.html.erb
<%= form_for @character do |c| %>
  <div class="form-group">
    <%= c.label :name %>
    <%= c.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= c.label :character_class %>
    <%= c.text_field :character_class, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= c.label :description %>
    <%= c.text_area :description, class: "form-control", rows: 4 %>
  </div>
  <div class="form-group">
    <%= c.label :physical %>
    <%= c.text_field :physical, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= c.label :social_skills %>
    <%= c.text_field :social_skills, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= c.label :magical_abilities %>
    <%= c.text_field :magical_abilities, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= c.submit "Create the character", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/characters/search.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Class</th>
      <th>Description</th>
      <th>Physical</th>
      <th>Social skills</th>
      <th>Magical abilities</th>
    </tr>
  </thead>
  <tbody>
    <% @search_result.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.character_class %></td>
        <td><%= character.description %></td>
        <td><%= character.physical %></td>
        <td><%= character.social_skills %></td>
        <td><%= character.magical_abilities %></td>
        <td><%= button_to "Remove", character, method: :delete, data: { confirm: "Remove #{character.name}?" }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Criate new character", new_character_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EP3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= nav_bar brand: "CRUDster", brand_link: root_url do %>
    <%= form_tag search_character_path, method: :get, class: "navbar-form navbar-right" do %>
      <div class="form-group">
        <%= text_field_tag :term, @search_term, class: "form-control" %>
        <%= button_to "Search", nil, class: "btn btn-default" %>
      </div>
    <% end %>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>